### PR TITLE
fix build and make html

### PR DESCRIPTION
**Pull request by thet**
This fixes https://github.com/plone/sphinx.themes.plone/issues/53 for me.

### CODE REVIEW

**Review by svx — APPROVED** [review]
LGTM !

Thanks !

**Comment by svx** [comment]
@thet would you mind to update the changelog ?

Thanks !

**Comment by svx** [comment]
FYI: we renamed the repo to fix some pip issues, I think you have to rebase :)

**Comment by thet** [comment]
@svx done! I'm merging.

As you have seen, I use the versions.cfg from buildout.coredev from github. This is much more up to date than the latest release of Plone 5.1. When Plone 5.1 RC is out, we can change again to: http://dist.plone.org/release/5.1-latest/versions.cfg

IMO, the requirements.txt should also come from a remote source to avoid updating that file (as long as it's not needed otherwise). The README.rst should than say (line 66):

```
    $ pip install -r https://raw.githubusercontent.com/plone/buildout.coredev/5.1/requirements.txt
```

Or better, 

```
    $ pip install -r http://dist.plone.org/release/5.1-latest/requirements.cfg
```

The latter would need the @plone/release-team to release that file too.

**Comment by svx** [comment]
@thet OK ! Great ! 

I will change the README and the docs to tell the right pip install URL ! 

Thanks !

**Comment by thet** [comment]
@svx - that's my opinion. Many people won't rely on external services like that. But we need net-access anyways, so...

**Comment by svx** [comment]
+1 !

With this way we 'only' need to maintain the versions on one place and we need net anyway for building, I changed the README and the docs already :)

**Pull request merged**
